// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmHVhIvwr9fObH6Q-fN-FE-g9JE1un4A',
    appId: '1:283373774641:web:5dff2fb4adaa7276edf210',
    messagingSenderId: '283373774641',
    projectId: 'chessnect',
    authDomain: 'chessnect.firebaseapp.com',
    storageBucket: 'chessnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxlZ6khk3WTPswqHImzMzJKRMMfk9RaNk',
    appId: '1:283373774641:android:fb07f5f515499d46edf210',
    messagingSenderId: '283373774641',
    projectId: 'chessnect',
    storageBucket: 'chessnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFwXNvmI0fVkEOjcPapHwL536GY6XCyk',
    appId: '1:283373774641:ios:42314263aaa6b60bedf210',
    messagingSenderId: '283373774641',
    projectId: 'chessnect',
    storageBucket: 'chessnect.firebasestorage.app',
    iosBundleId: 'com.example.chessApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdFwXNvmI0fVkEOjcPapHwL536GY6XCyk',
    appId: '1:283373774641:ios:42314263aaa6b60bedf210',
    messagingSenderId: '283373774641',
    projectId: 'chessnect',
    storageBucket: 'chessnect.firebasestorage.app',
    iosBundleId: 'com.example.chessApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxmHVhIvwr9fObH6Q-fN-FE-g9JE1un4A',
    appId: '1:283373774641:web:70e00dbf9fdaadb6edf210',
    messagingSenderId: '283373774641',
    projectId: 'chessnect',
    authDomain: 'chessnect.firebaseapp.com',
    storageBucket: 'chessnect.firebasestorage.app',
  );

}